### ISSUE TITLE
Better GraalVM support

### ISSUE THREAD

**Issue by Shpota** [GetStream/stream-java#100]
While migrating an application to GraalVM I found several issues with the GetStream Java client. 

I had to manually include the `stream-java2.info` file into the binary. Also I had to register several classes for reflection: `io.getstream.core.models.serialization.DataDeserializer` and 11 anonymous classes of `io.getstream.core.Stream`.

All these procedures took a lot of time to figure out. It would be great if you could solve them on the library side so that the clients wouldn't have to spend time resolving incompatibilities.

**Comment by ferhatelmas** [comment]
We don't have the expertise for GraalVM so if you want to contribute a how-to doc, we're happy to integrate. Thanks!
