### ISSUE TITLE
updating user resets all other values for that user

### ISSUE THREAD

**Issue by ishaangarg** [GetStream/stream-java#115]
Using update like so:
```
client.user("123").update(new Data()
        .set("bio", "pikachu")).join();
```
empties all other values for that particular user. So when updating 'bio' for a user, their 'name', 'gender' etc gets deleted.

As a workaround, fetching the user Data obj first, then updating the key's value in that Data obj, and updating user with the full Data obj works as expected.

**Comment by ferhatelmas** [comment]
Your workaround is correct because it's the behavior at the moment in the API.

Since it's related to API, not SDK, I would close this issue. If API is changed, it will be reflected in SDKs in bulk.
