### ISSUE TITLE
I can't get messages sent to a channel using the java sdk.

### ISSUE THREAD

**Issue by realninety5** [GetStream/stream-java#145]
Hello getstream, I am having a problem getting messages sent to a channel using the java sdk. When I call '.getMembers()', I get the list of members, but when I call '.getMessages()', it always returns an empty list even though there are messages in it.

**Comment by JimmyPettersson85** [comment]
Hey @realninety5  this is the SDK for Feeds, I think you want the one for [chat](https://github.com/GetStream/stream-chat-java).

**Comment by realninety5** [comment]
Okay, thanks.
