### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sirio7g** [GetStream/stream-java#21]
![feed1](https://cloud.githubusercontent.com/assets/1384900/15708183/66a951dc-27fd-11e6-8d0f-7deb387670a6.png)

**Comment by sirio7g** [comment]
![screenshot at jun 06 19-46-23](https://cloud.githubusercontent.com/assets/1384900/15831752/62d35bcc-2c1f-11e6-9ecf-5210167645b5.png)

**Comment by tschellenbach** [comment]
@sirio7g this is a public repo, not a good screenshot to post :)
