### ISSUE TITLE
What's the difference between FlatActivityServiceImpl and UserActivityServiceImpl?

### ISSUE THREAD

**Issue by awkejiang** [GetStream/stream-java#24]
There are four built-in feed groups. So there are four different implementation:
FlatActivityServiceImpl,
AggregatedActivityServiceImpl,
UserActivityServiceImpl,
NotificationActivityServiceImpl.

But what's the difference between FlatActivityServiceImpl and UserActivityServiceImpl. I cannot see any difference from their implementations.

**Comment by sirio7g** [comment]
There's no difference. UserActivity is there for backwards compatibility but it does no longer exits on both client and server side.
