### ISSUE TITLE
Java SDK is out of sync for region support

### ISSUE THREAD

**Issue by iandouglas** [GetStream/stream-java#28]
Had a customer report that the Java SDK is supporting regions that time out. Can you please update the SDK to reflect our current regions?

https://github.com/GetStream/stream-java/blob/6de5d72a49930335e5f615500d74865eb684540d/stream-core/src/main/java/io/getstream/client/config/StreamRegion.java#L15-L17

**Comment by sirio7g** [comment]
Regions are already in sync with the current CDN settings.

I'd suggest to change the default timeouts. Older releases of stream-java had a pretty aggressive timeouts. Please have a look at the code snippet below:

```java
    /**
     * Get default client configuration.
     * @return Default configuration
     */
    public ClientConfiguration getClientConfiguration() {
        ClientConfiguration configuration = new ClientConfiguration(StreamRegion.EU_WEST);
        
        /* timeouts in milliseconds */
        configuration.setConnectionTimeout(10000); 
        configuration.setTimeout(10000);
        return configuration;
    }
```
