### ISSUE TITLE
Verb property instead of Type property 

### ISSUE THREAD

**Issue by guillaumegarcia13** [GetStream/stream-java#32]
Hi,
In the example regarding MixedType, shouldn't it be 
`@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "verb")`
instead of current
`@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")`

Thanks in advance.

**Comment by dwightgunning** [comment]
Just to clarify, are you referring to [MixedType.java#L86](https://github.com/GetStream/stream-java/blob/1cd06d310c24db95bbbff18e2921e8d1fa475671/stream-repo-apache/src/test/java/io/getstream/client/apache/example/mixtype/MixedType.java#L86)?

This example is demonstrating that different types of Activities can be added / retrieved from the feed, using a customer property on the Activity. In this example we use the `type` customer field to enable our app to distinguish between the activity types (the name of the field is arbitrary).

Verbs are a separate mandatory field for Activities. In this example the verb of the activities isn't so important so we just set the value to "verb". Perhaps that's confusing; it might be better set to a value that relates to the "sport match" metaphor, such as "match_finished".

**Comment by guillaumegarcia13** [comment]
Hi,

Absolutely, that was the line.
Sorry, my understanding from the "Getting Started" demo was that "verb" was used to differentiate exactly this. ("tweet" vs "watch")

Thanks for clarifying.
I can close the this "issue" then.

**Comment by dwightgunning** [comment]
No problem at all. Thanks for raising the question in any case. We're happy to help.
