### ISSUE TITLE
mark_seen and mark_read with Activity Group Ids

### ISSUE THREAD

**Issue by dwightgunning** [GetStream/stream-java#35]
The API and examples imply that Notification Feed activities can be marked seen / read by sending a list of Activity Ids. However the endpoint expects the Id at the "group" level.

**Comment by dwightgunning** [comment]
Housekeeping close.

**Comment by fungchun1121** [comment]
Why is this closed? This issue has not been resolved!

**Comment by Nekuromento** [comment]
@fungchun1121 This is documented in the official docs (https://getstream.io/docs/#notification-feeds)
Only whole activity groups could be marked as read/seen
You could remove the activity by ID from the notification feed instead

**Comment by fungchun1121** [comment]
Yes, I would like to mark an entire activity group as seen/read. However, I do not see any ID in the [NotificationGroup class](https://github.com/GetStream/stream-java/blob/master/src/main/java/io/getstream/core/models/NotificationGroup.java). Please can you advise where I can get back the Activity Group ID?  Thanks!

**Comment by Nekuromento** [comment]
@fungchun1121 `NotificationGroup` extends `Group` class which has `getGroup` method returning group ID - https://github.com/GetStream/stream-java/blob/master/src/main/java/io/getstream/core/models/Group.java#L48L50

**Comment by fungchun1121** [comment]
@Nekuromento Yes but here's the problem. The `getGroup` method only returns part of the entire group ID, e.g. for a group ID `57fb01fb-ec40-11e9-8080-800027aa5748.follow_2019-10-11` only `follow_2019-10-11` will be returned and if I use this to call `feed.getActivities(new ActivityMarker().seen("follow_2019-10-11")).join();` I will get this error `java8.util.concurrent.CompletionException: io.getstream.core.exceptions.StreamAPIException: InputException: "follow_2019-10-11" is not a valid UUID (code = 4 status = 400)`. 

Please can you advise a feasible way to obtain the group ID?

**Comment by fungchun1121** [comment]
@Nekuromento Just one thing to add: I would like to aggregate some certain groups of activities so using individual activity ID for the group ID would not work for me here. Thanks so much for your attention. I look forward to your reply :)

**Comment by Nekuromento** [comment]
@fungchun1121 This is indeed a bug. Thanks for reporting this. I will fix this shortly and release a new library version

**Comment by fungchun1121** [comment]
@Nekuromento Thank you very much Max! Have a great one!!

**Comment by Nekuromento** [comment]
@fungchun1121 I have published a new version `3.1.10` with new `getID` and `getGroupID` methods available for `Group` class. It should be available from maven in ~1 hour

**Comment by fungchun1121** [comment]
@Nekuromento Thanks a lot for the prompt fix. Will let you know if any further issue :)
