### ISSUE TITLE
JWT token expiration

### ISSUE THREAD

**Issue by sheng-duetto** [GetStream/stream-java#53]
JWT tokens supports a `withExpiresAt` options see [here](https://github.com/auth0/java-jwt/blob/8ca949eebe0d186567be72343c6e548ade001bd6/lib/src/main/java/com/auth0/jwt/JWTCreator.java#L129)

Is it possible to add support for this in as an extension or a similar method to https://github.com/GetStream/stream-java/blob/6645fce4d648c8c4e3ec97b5f38543a8f28d312f/src/main/java/io/getstream/core/utils/Auth.java#L115-L114 ?

I've also seen this option is available in stream clients in other lang (e.g. [ruby](https://github.com/GetStream/stream-ruby/blob/ff35a734d00ff24279bd99b1f0084214a561119d/lib/stream/client.rb#L91))

We want to leverage this so that if a malicious user were to access the token, they won't always have access to notification data. The default of a never expiring token seems too lax.

**Comment by Nekuromento** [comment]
Added overloads for frontend token generation methods in new `3.1.7` release:
See https://getstream.github.io/stream-java/io/getstream/core/utils/Auth.html#buildFrontendToken-java.lang.String-java.lang.String-java.util.Date- and https://getstream.github.io/stream-java/io/getstream/client/Client.html#frontendToken-java.lang.String-java.util.Date-

**Comment by sheng-duetto** [comment]
Awesome tyvm!
