### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [GetStream/stream-java#54]
Hi
The following lines have cryptographic API misuses. <br> File name => stream-core/src/main/java/io/getstream/client/util/HttpSignatureHandler.java: Line number => 30: API name => SecretKeySpec:<BR> File name => stream-core/src/main/java/io/getstream/client/util/HttpSignatureHandler.java: Line number => 30: API name => SecretKeySpec:<BR> File name => stream-repo-apache/src/main/java/io/getstream/client/apache/repo/utils/SignatureUtils.java: Line number => 62: API name => SecretKeySpec:<BR> File name => stream-repo-apache/src/main/java/io/getstream/client/apache/repo/utils/SignatureUtils.java: Line number => 69: API name => MessageDigest:<BR> File name => stream-repo-apache/src/main/java/io/getstream/client/apache/repo/utils/SignatureUtils.java: Line number => 69: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => stream-repo-apache/src/main/java/io/getstream/client/apache/repo/utils/SignatureUtils.java: Line number => 62: API name => SecretKeySpec:<BR> File name => stream-repo-apache/src/main/java/io/getstream/client/apache/repo/utils/SignatureUtils.java: Line number => 69: API name => MessageDigest:<BR> File name => stream-repo-okhttp/src/main/java/io/getstream/client/okhttp/repo/utils/SignatureUtils.java: Line number => 61: API name => SecretKeySpec:<BR> File name => stream-repo-okhttp/src/main/java/io/getstream/client/okhttp/repo/utils/SignatureUtils.java: Line number => 68: API name => MessageDigest:<BR> File name => stream-repo-okhttp/src/main/java/io/getstream/client/okhttp/repo/utils/SignatureUtils.java: Line number => 68: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => stream-repo-okhttp/src/main/java/io/getstream/client/okhttp/repo/utils/SignatureUtils.java: Line number => 61: API name => SecretKeySpec:<BR> File name => stream-repo-okhttp/src/main/java/io/getstream/client/okhttp/repo/utils/SignatureUtils.java: Line number => 68: API name => MessageDigest:<BR>

**Comment by Nekuromento** [comment]
Thank you for submitting this issue. You reference older version of the library which is no longer supported.
