### ISSUE TITLE
How I could subscribe to changes like Javascript does

### ISSUE THREAD

**Issue by cbedoy** [GetStream/stream-java#55]
Hi everyone!

To be honest I see that you have a little docs outdated and some cases merged docs between clients, so thats why my question. For example in the docs you have the option for _subscribe to changes_ from any notification feed, but it's only for _javascript_. 

So I'd like to know if exist any way to listening flat feed changes? or to listening reactions, comments or those kind of changes? I know you have **React Native** component but all our core app is on Kotlin and java, so that's why need a native.

You have this:

**Subscribe to realtime updates via API client**

```
let notificationFeed = client.feed('notification', '1');

function callback(data) {
    console.log(data);
}

function successCallback() {
    console.log('now listening to changes in realtime');
}

function failCallback(data) {
    alert('something went wrong, check the console logs');
    console.log(data);
}

user1.subscribe(callback).then(successCallback, failCallback);
```

And

**Subscribe to realtime updates using UMD script**

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/getstream/dist/js_min/getstream.js">
</script>

<script type="text/javascript">
    var client = stream.connect('n6dqxby6gcfa', userToken, '49021');
    var notificationFeed = client.feed('notification', '1');

    function callback(data) {
        console.log(data);
    }

    function successCallback() {
        console.log('now listening to changes in realtime');
    }

    function failCallback(data) {
        alert('something went wrong, check the console logs');
        console.log(data);
    }

    notificationFeed.subscribe(callback).then(successCallback, failCallback);
</script>
```

Exist any way to implement with java?

**Comment by Nekuromento** [comment]
At the moment java client doesn't support realtime updates out of the box. You could subscribe to changes using a Faye client. You can find authentication details in our JS client https://github.com/GetStream/stream-js/blob/783a5ba8c8c4d4b4fb7a4e47aff780d415cd1956/src/lib/client.js#L515L562
Alternatively you can use other transports like webhooks or Amazon SQS - https://getstream.io/docs/#realtime-introduction

**Comment by HeinHtetZaw99** [comment]
Is that feature supported for now ?? For Kotlin ??
