### ISSUE TITLE
Frontend token support

### ISSUE THREAD

**Issue by psylinse** [GetStream/stream-java#56]
Does this library support making calls via the frontend token? I'm looking at embedding this in a mobile application and I don't see how this is done. Apologies if I'm missing something obvious!

**Comment by Nekuromento** [comment]
@psylinse there’s a mobile ready client available in the `io.stream.cloud` package https://getstream.github.io/stream-java/io/getstream/cloud/package-summary.html
There you can find a set of classes with `Cloud` prefix that mirror the hierarchy in the `io.getstream.client` package

**Comment by psylinse** [comment]
Ah perfect, thank you!
