### ISSUE TITLE
Attribute "id" in data causes exception

### ISSUE THREAD

**Issue by foscocorazza** [GetStream/stream-java#57]
In my android app, I am trying to retrieve some enriched activities from a feed, simply declared:
`feed = client.notificationFeed("notification");`

Then I retrieve the notification groups with:

```
try {
    ActivityMarker marker = new ActivityMarker();
    CompletableFuture<List<NotificationGroup<EnrichedActivity>>> future = feed.getEnrichedActivities(marker.allSeen());

    List<NotificationGroup<EnrichedActivity>> groups = future.get();

    // Do something with ´groups´

} catch (StreamException e) {
    callback.onResult(null); 
} catch (InterruptedException e) {
    e.printStackTrace();
} catch (ExecutionException e) {
    e.printStackTrace();
}
```

And then of course use `groups`.

For some users, it works flawlessly. Some others, an ExecutionException is caught:
`java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: Key can't be named 'id' (through reference chain: java.util.ArrayList[6]->io.getstream.core.models.NotificationGroup["activities"]->java.util.ArrayList[0]->io.getstream.core.models.EnrichedActivity$Builder["actor"])`

I then check how that activity's actor looks like and is something along these lines:

```
{ 
   "created_at":"2019-12-09T23:39:31.995179Z",
   "updated_at":"2019-12-09T23:39:31.995179Z",
   "id":"user-123456",
   "data":{ 
      "id":"user-123456",      <- Hey, here's a problem!
      "name":"My Name Here",
      "some_other_data":"here"
   }
}
```

Maybe id is a keyword, or maybe the actor gets flattened and there's a dupe. How can I get that activity anyway? I can totally get rid of that "id", I don't need that info. But how can I retrieve unflattened data, OR, "data" as a string, or some other workaround?

**Comment by harrunisk** [comment]
Hi @foscocorazza ,
Were you able to fix the problem?  I am getting the same error.

**Comment by ferhatelmas** [comment]
There was a change in the maintenance of this client, sorry for a slow reply on this ticket. 

It smells like reserved field names are used.
Could you provide some details like app id/feed group/feed id so that I can check?

Regarding getting activities directly, similar to `updateActivities`, there should be `getActivities` since supported by REST api but missing in the SDK. We can add them but let's fix the exception first for you.

**Comment by acron0** [comment]
We're receiving this exception as of 23rd Dec. `getActivities` is fine, but `getEnrichedActivities` throws with the same error:

```
Execution error (IllegalArgumentException) at com.google.common.base.Preconditions/checkArgument (Preconditions.java:142).
Key can't be named 'id'
```

It's unclear to us how to even identify the problematic objects, let alone how to fix them. Advice would be greatly appreciated.

**Comment by ferhatelmas** [comment]
Server relaxed the requirement of fields in data. SDK needs an update, coming today.

**Comment by acron0** [comment]
@ferhatelmas Any update?

**Comment by ferhatelmas** [comment]
Give a try to `3.3.0` and let me know, thanks!
