### ISSUE TITLE
Integration of getstream.io feeds not working in android

### ISSUE THREAD

**Issue by tonyjoy1100** [GetStream/stream-java#59]
Client client =  Client.builder(apikey, apikeySecret).build();
FlatFeed user = client.flatFeed("timeline", userId);
List<Activity> response = user.getActivities().join();

**I found Error where the ' user.getActivities().join()' code works and crashes,which is given below.**

> E/AndroidRuntime: FATAL EXCEPTION: main
>     java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
>         at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:330)
>         at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:24)
>         at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
>         at io.getstream.core.utils.Auth.buildBackendToken(Auth.java:135)
>         at io.getstream.core.utils.Auth.buildBackendToken(Auth.java:123)
>         at io.getstream.core.utils.Auth.buildFeedToken(Auth.java:60)
>         at io.getstream.client.Client.getActivities(Client.java:212)
>         at io.getstream.client.FlatFeed.getActivities(FlatFeed.java:51)
>         at io.getstream.client.FlatFeed.getActivities(FlatFeed.java:23)

there is no code to integrate appid and token which is created from the backend.can u give me a solution for this?

**Comment by tbarbugli** [comment]
@Nekuromento any idea on this?

**Comment by tonyjoy1100** [comment]
there is no way to integrate this in android, but you get apis of getstrem when it integrate this on web and datas can be listed from this responce in android.

**Comment by Nekuromento** [comment]
@tonyjoy1100 On android you have to use `io.getstream.cloud.CloudClient`
This class provides mostly the same features as `io.getstream.client.Client` but is specifically created for client-side Android usage (see https://getstream.github.io/stream-java/io/getstream/cloud/CloudClient.html)

```java
CloudClient client = CloudClient.builder(apiKey, token, userID).build();
CloudFlatFeed user = client.flatFeed("timeline");
List<Activity> response = user.getActivities().join();
```

**Comment by tbarbugli** [comment]
@Nekuromento can you add a section on the readme about this? ie. "How to use this on Android"
