### ISSUE TITLE
NotAllowedException: You do not have permission to do this, you got this error because there are no policies allowing this request on this application.

### ISSUE THREAD

**Issue by klaszlo8207** [GetStream/stream-java#77]
NotAllowedException: You do not have permission to do this, you got this error because there are no policies allowing this request on this application.

        val client = CloudClient.builder(API_KEY, token, user).build()
        return client.flatFeed(team, "user_one").getActivities(Limit(25)).join()

**team is my  group name
user_one is the user name**

Also, How can I get all feeds of all users in "team" group?

Thanks

**Comment by ferhatelmas** [comment]
By default, `user` feed group has permission to be read other users. 
In your case, feed group is custom (`team`) and unless token (`user`) is generated for `user_one`, it's normal to see this exception until contacting [support](https://getstream.io/support) to get that policy added into your application. Ensure to provide your app id, feed group and details of the policy you want.

**Comment by ferhatelmas** [comment]
> Also, How can I get all feeds of all users in "team" group?

It's probably better to ask this on stackoverflow in general since it's a how-to. 

However, here, let's give a try to answer but unfortunately, not very clear to me. Are you asking if there is a search API for existing feeds?

**Comment by klaszlo8207** [comment]
I read that I can't show other elses feeds in my android application (flutter). 

https://stackoverflow.com/questions/60847164/im-getting-a-notallowedexception-when-retrieving-activities-from-feed-collectio

I am always getting 'NotAllowedException' when I want to show other user feed. **Any way to set the default policy to ALLOW to all my newly generated GROUP_NAME?**  

**Also Is there any way to show all feeds (all user's message) in a group?**

Thanks,
Leslie

**Comment by klaszlo8207** [comment]
So basically will be an admin panel in our server where we want to create GROUPS on the fly, and we need to ALLOW this thing on that. One by one is not a solution for us. 

Thanks

**Comment by klaszlo8207** [comment]
Also in the getStream admin panel I see only:

App overview / Data Explorer / All

group:user

and the filter

group:*

group:all

not working



ferhat elmas <notifications@github.com> ezt írta (időpont: 2020. márc. 31.,
K, 10:51):
