### ISSUE TITLE
Overall reaction add request is slow

### ISSUE THREAD

**Issue by klaszlo8207** [GetStream/stream-java#80]
```
        println("-------- Execution time2: " + (System.currentTimeMillis() - start).toString() + "ms")
->        val r = client.reactions().add(user, like).get()
        println("-------- Execution time3: " + (System.currentTimeMillis() - start).toString() + "ms")

```
this line is causing a 600ms delay

any way to make it faster?

**Comment by ferhatelmas** [comment]
@klaszlo8207 You're checking network latency + processing time. We return processing time in the `duration` field of response. Could you check if it's low enough for you? 

If you give me your app id, I can also provide some statistic from server point of view in an aggregated fashion. 

Improving network speed is out of scope and it's a complex topic. However, as a starting point, ensure to have your app in the closest region. If you're in Europe for example, you might want to host your app in USA.

**Comment by klaszlo8207** [comment]
Ok, the java library is ultra slow. Because I used flutter and dart and methodchannels with kotlin... I updated my code to use only http calls, not the slow java library.

My delay is now 200-300ms instead of 600

**Comment by ferhatelmas** [comment]
Great to hear. 

According to payload size, JSON processing can matter but I wouldn't expect that much actually.
