### ISSUE TITLE
NotAllowedException: token contains an invalid number of segments (code = 17 status = 403)

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-java#84]
I keep getting this error NotAllowedException: token contains an invalid number of segments (code = 17 status = 403) when trying to use this with Flutter via Android Kotlin. I am using JS and Firebase Functions as the backend.

`
const client = stream.connect(STREAM_API_KEY, STREAM_API_SECRET, STREAM_APP_ID);

        var make = await client.user(userId).getOrCreate({userId});
        const token = client.createUserToken(userId);
        console.log(make.id);
        console.log(token);
        return Promise.all([make]).then(() => {
            return {token, api: STREAM_API_KEY, appId: STREAM_APP_ID};
        });`
It does return the token but the issue remains.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5956'>Zendesk ticket #5956</a>:<br><br>Hi Rickey

Thanks for reaching to us.
Can you please share your User ID, App Id, and Token you are trying with?
I can get this checked for you.

Cheers
Seetha

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5956'>Zendesk ticket #5956</a>:<br><br>Hi Rickey

I am marking this ticket as closed since we had this discussion through our support channel.

Please feel free to get in touch.

Cheers
Seetha

**Comment by devsideal** [comment]
@shodgetts what was the fix for this issue, I'm also getting same issue in my Android app, I'm using `CloudClient`

```
public void getActivities() throws Exception{
        CloudClient client = CloudClient.builder(apiKey, secret, "chris" ).build();
        CloudFlatFeed chris = client.flatFeed("user", "chris");
        // Add an Activity; message is a custom field - tip: you can add unlimited
        // custom fields!
        chris.addActivity(Activity.builder().actor("chris").verb("add").object("picture:10").foreignID("picture:10")
                .extraField("message", "Beautiful bird!").build());

        // Create a following relationship between Jack's "timeline" feed and Chris'
        // "user" feed:
        CloudFlatFeed jack = client.flatFeed("timeline", "jack");
        jack.follow(chris);

        // Read Jack's timeline and Chris' post appears in the feed:
        List<Activity> response = jack.getActivities(new Limit(10)).join();
        for (Activity activity : response) {
            System.out.println("Post: "+activity.getExtra().get("message"));
        }
    }
```

```
io.getstream.core.exceptions.StreamAPIException: NotAllowedException: token contains an invalid number of segments (code = 17 status = 403)
java8.util.concurrent.CompletionException: io.getstream.core.exceptions.StreamAPIException: NotAllowedException: token contains an invalid number of segments (code = 17 status = 403)
	at app//io.getstream.cloud.CloudFlatFeed.lambda$getActivities$0(CloudFlatFeed.java:107)
	at app//java8.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:630)
	at app//java8.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:504)
	at app//java8.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at app//io.getstream.core.http.OKHTTPClientAdapter$1.onResponse(OKHTTPClientAdapter.java:109)
	at app//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
```
