### ISSUE TITLE
Issue on converting EnrichedActivity to String

### ISSUE THREAD

**Issue by altayhunoglu** [GetStream/stream-java#90]
I need to convert EnrichedActivity to String as I use stream-java:3.2.4 in a Flutter application.

I get EnrichedActivity list like this:

   ```
     val list : List<EnrichedActivity> =   client.flatFeed("user").getEnrichedActivities(EnrichmentFlags()
                .withOwnReactions()
                .withRecentReactions()
                .withReactionCounts()).get()
```

Then I try to convert the list like this:
```
    val resultString = ObjectMapper()
                        .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.ALWAYS)
                        .writeValueAsString(list)
```

But some fields are erased by FasterXml-jackson (v2.9.6). 

**Isn't this the correct way to convert an EnrichedActivity list to String?**

----------

Note: 
**1- Original EnrichedActivity :**

  {EnrichedActivity@15673} "EnrichedActivity{id=5e02d656-27ef-11eb-88f9-128a130028af, actor=Data{id=RqO5ns7mrYfvain3ETQpdPgIQZz1, data={updated_at=2020-11-11T22:46:38.568116Z, name=RqO5ns7mrYfvain3ETQpdPgIQZz1, created_at=2020-11-11T22:46:38.568116Z}}, verb=post, object=Data{id=b0e249e9-8695-4161-bb24-d3980da4cdeb, data={}}, foreignID=, target=Data{id=, data={}}, time=Mon Nov 16 12:37:39 GMT+03:00 2020, origin=null, to=null, score=null, **ownReactions**={like=[Reaction{id=4186ea14-f3e5-4368-8a91-eafc12e3045b, appID=null, kind=like, userID=RqO5ns7mrYfvain3ETQpdPgIQZz1, activityID=5e02d656-27ef-11eb-88f9-128a130028af, parent=, ownChildren=null, latestChildren={}, childrenCounts={}, userData=Data{id=RqO5ns7mrYfvain3ETQpdPgIQZz1, data={updated_at=2020-11-11T22:46:38.568116Z, name=RqO5ns7mrYfvain3ETQpdPgIQZz1, created_at=2020-11-11T22:46:38.568116Z}}, activityData={}, extra={updated_at=2020-11-16T09:39:25.088760Z, created_at=2020-11-16T09:39:25.088760Z}}]}, **latestReactions**={like=[Reaction{id=4186ea14-f3e5-4368-8a91-eafc12"

**2- The serialized form of the list:**

[
  {
    "actor": {
      "id": "RqO5ns7mrYfvain3ETQpdPgIQZz1",
      "updated_at": "2020-11-11T22:46:38.568116Z",
      "name": "RqO5ns7mrYfvain3ETQpdPgIQZz1",
      "created_at": "2020-11-11T22:46:38.568116Z"
    },
    "id": "5e02d656-27ef-11eb-88f9-128a130028af",
    "object": {
      "id": "b0e249e9-8695-4161-bb24-d3980da4cdeb"
    },
    "target": {
      "id": ""
    },
    "time": "2020-11-16T09:37:39.284",
    "verb": "post",
    "foreign_id": "",
    "message": "test2",
    "**latest_reactions_extra**": {
      "like": {
        "next": ""
      }
    }
  }
]

**Comment by altayhunoglu** [comment]
Stackoverflow link for the same question:
https://stackoverflow.com/questions/64921368/issue-on-converting-enrichedactivity-to-string

**Comment by ferhatelmas** [comment]
@altayhunoglu are you trying to convert to string from server so that you can use flutter client ?

Could you also edit the issue a bit to highlight the diff ? Thanks in advance!

**Comment by altayhunoglu** [comment]
Hello Ferhat,

 Thanks for your attention.

 To make it cleaner, I have reduced the list to include just one EnrichedActivity and highlighted those two fields which I need particularly.

 As you see, **ownReactions** field is removed in the JSON String form and **latestReactions** field has a different value than expected.

I use  stream-java:3.2.4 in Kotlin (MainActivity.kt) layer of Flutter. I get the EnrichedActivity list and convert it to JSON String transmitting it to Dart layer (as currently there is no Flutter library for Activity Feeds yet, so far as I know.)

(Note: I think, another guy had the same problem as me and he solved the problem using another JSON converter. But I think it would be better to use the standard FasterXML way.
Link for this guys issue: 
https://stackoverflow.com/questions/61168851/getstream-io-get-like-count-and-users-who-liked)

**Comment by altayhunoglu** [comment]
When I use Gson instead of FasterXML, it is converted without any problem by the way

**Comment by ferhatelmas** [comment]
Good to hear, it's resolved.
