### ISSUE TITLE
while create user its not showing on dashboard 

### ISSUE THREAD

**Issue by puneet-raj** [GetStream/stream-java#91]
CompletableFuture<Data> clientData=client
	        .user("12233").getOrCreate(new Data()
	                .set("name", "XYZ" )
	                .set("role", "user"));
			LOGGER.info("Id {} , data {}, token {}",clientData.get().getID(),clientData.get().getData().toString(),client.frontendToken(userProfile.getUserId()));

gz#9185

**Comment by ferhatelmas** [comment]
`Users`/`Collections`/`Reactions` are not shown in the dashboard yet. It's in the backlog and dashboard team is working on it.

I will close this issue since it's related to this SDK. If you have any other issues, let me know though.
