### ISSUE TITLE
Activity exists after being deleted

### ISSUE THREAD

**Issue by natete** [GetStream/stream-java#93]
Hello, I am having an issue deleting an activity.

Let´s say I have an activity in the user feed and I try to delete it:

`client.flatFeed(feed).removeActivityByID(activityId.getValue()).join();`

Then if I try to check if the activity exists I get the activity back:

`client.flatFeed(feed).getActivities(new Filter().idGreaterThanEqual(activityId.getValue())).join()`

I get it as many times as I request it. But, if I repeat the process, I don't get the activity anymore.

Or if I request the feed activities without the filter it is not there and, if after that I repeat the request with the filter, I don't get it anymore.

`client.flatFeed(feed).getActivities().join()`

gz#12262

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/12262'>Zendesk ticket #12262</a>:<br><br>Hello and thanks for submitting an issue to our GitHub repository.

We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
<br><p><em><small>°°°</small></em></p>

**Comment by ferhatelmas** [comment]
It's for consistent pagination. When filter is removed, there is no pagination and you can see the updated data.

If needed, you can force via `refresh=true` query param.
