### ISSUE TITLE
ownChildren for reactions is null

### ISSUE THREAD

**Issue by ude** [GetStream/stream-java#96]
I have a feed and I'm implementing the logic add reactions to reactions (i.e. liking post comments).
When getting the coments for a certain post i set the filter with:
.filter(LookupKind.ACTIVITY, {postId}, DEFAULT, limit, "comment")

In the result "ownChildren" is always null. I would expect it to contain data if I had liked the comment (this is the behaviour in iOS).

I need that in order to identify the post I've liked. 

How can I get my own reactions to to reactions?

Cheers

gz#12930

**Comment by shodgetts** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/12930'>Zendesk ticket #12930</a>:<br><br>Hello,
We will look into this use case and get back to you as soon as we can.

Best,
Cody
<br><p><em><small>°°°</small></em></p>

**Comment by monstaro** [comment]
Hello @ude 
To further assist you with this issue, could you send an email to support@getstream.io and include the app_id, user_id, feed group, and feed id you are experiencing this with? 
Once we have this information in our support system we will investigate this further.

Best Regards,
Cody

**Comment by ferhatelmas** [comment]
This is a server sdk so it needs to pass user id additionally. Needs a fix.
